# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#56949f" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#ea9d34", bold = true, italic = true, underline = true }
find_position = { fg = "#d7827e", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#56949f", bg = "#56949f" }
marker_cut = { fg = "#b4637a", bg = "#b4637a" }
marker_marked = { fg = "#56949f", bg = "#56949f" }
marker_selected = { fg = "#ea9d34", bg = "#ea9d34" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#faf4ed", bg = "#56949f" }
count_cut = { fg = "#faf4ed", bg = "#b4637a" }
count_selected = { fg = "#faf4ed", bg = "#ea9d34" }

# Border
border_symbol = "│"
border_style = { fg = "#908caa" }

# Highlighting
syntect_theme = "~/.config/yazi/rose-pine-dawn.tmTheme"

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#faf4ed", bg = "#286983", bold = true }
inactive = { fg = "#286983", bg = "#f4ede8" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#faf4ed", bg = "#286983", bold = true }
normal_alt = { fg = "#286983", bg = "#f4ede8" }

# Select mode
select_main = { fg = "#faf4ed", bg = "#56949f", bold = true }
select_alt = { fg = "#56949f", bg = "#f4ede8" }

# Unset mode
unset_main = { fg = "#faf4ed", bg = "#d7827e", bold = true }
unset_alt = { fg = "#d7827e", bg = "#f4ede8" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep = { fg = "#908caa" }
perm_type = { fg = "#286983" }
perm_read = { fg = "#ea9d34" }
perm_write = { fg = "#b4637a" }
perm_exec = { fg = "#56949f" }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#286983", bg = "#dfdad9" }
progress_error = { fg = "#b4637a", bg = "#dfdad9" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#286983" }
active = { fg = "#d7827e", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#286983" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#286983" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#286983" }
title = {}
hovered = { fg = "#d7827e", underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#f4ede8" }
cand = { fg = "#56949f" }
rest = { fg = "#6e6a86" }
desc = { fg = "#d7827e" }
separator = "  "
separator_style = { fg = "#cecacd" }

# : }}}


# : Help {{{

[help]
on = { fg = "#56949f" }
run = { fg = "#d7827e" }
hovered = { reversed = true, bold = true }
footer = { fg = "#f4ede8", bg = "#575279" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#56949f" }
title_warn = { fg = "#ea9d34" }
title_error = { fg = "#b4637a" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#56949f" },

  # Media
  { mime = "{audio,video}/*", fg = "#ea9d34" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d7827e" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#56949f" },

  # Fallback
  { name = "*", fg = "#575279" },
  { name = "*/", fg = "#286983" },
]

# : }}}
